# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
    context-path: /freeter-generator

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        #url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&characterEncoding=UTF-8
        #username: root
        #password: sa
        url: jdbc:mysql://rm-wz9us3wej37qdt4ergo.mysql.rds.aliyuncs.com:3306/freetermart?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: rootuser
        password: $Sixeco2017!@)#$
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

